### ISSUE TITLE
Unreleased locks when Resque terminates using the loner option

### ISSUE THREAD

**Issue by tjsousa** [lantins/resque-lock-timeout#26]
Hi guys,

I've found an odd behaviour when using the [loner option](https://github.com/lantins/resque-lock-timeout#enqueued-exclusivity-loner-option), where unreleased locks (without timeout) can be stuck in Redis after a process termination occurs while Resque is enqueueing a job (Heroku deploy environment).

[After taking a look at the code](https://github.com/lantins/resque-lock-timeout/blob/master/lib/resque/plugins/lock_timeout.rb#L171-L181), I guess the issue is that the lock is being acquired during a `before_enqueue` hook, which, during a process termination, can complete successfully while the actual Resque enqueue operation doesn't (it's not transactional from what I know). After this, no new process can actually enqueue a similar job for execution as the lock is already in Redis, and subsequent jobs of the same kind will be inhibited forever.

I was wondering if a possible strategy to handle this situation could be done using a two-phase process where an `after_enqueue` hook could be used to finally acquire the lock after the actual job enqueue operation completed.

**Comment by lantins** [comment]
Hey @tjsousa 

I don't use `loner` myself, so its difficult for me to judge how this should be played out.

When the process is terminated and it gets 'stuck', do you know HOW its killed?

I'd love to see a PR on how this could be fixed :)
Or we can discuss it some more here and figure out a way together.

**Comment by edjames** [comment]
Hi

See my reply to another issue (which is pretty much the same behaviour you describe here):

https://github.com/lantins/resque-lock-timeout/issues/17

Hope that helps.

**Comment by tjsousa** [comment]
Thank you @edjames !

Although I have worked around this problem, it actually still persists. Looking at #17, my particular scenario does not use a hash as a parameter, so I'm not sure it has a common cause.

@lantins Answering your question, I know it happens when our app running in Heroku sends KILL signals to our Resque processes, although I wasn't able to pin-point the exact cause (as it only happens sometimes).

**Comment by lantins** [comment]
This reminds me of this issue: https://github.com/lantins/resque-retry/pull/61

**Comment by tjsousa** [comment]
@lantins, thanks to that share I was finally able to dedicate some time in replicating the issue and, in fact, was able to confirm the lack of lock removal in the case of a dirty exit (e.g. SIGKILL in the child job). 

Using a similar approach, we can do the lock cleanup from the worker process through a `on_failure` hook.
