### ISSUE TITLE
When a job is reserved but is found to be locked, it should be re-enqueued

### ISSUE THREAD

**Issue by sebbacon** [lantins/resque-lock-timeout#28]
When another job holds the lock, the [code returns nil](https://github.com/lantins/resque-lock-timeout/blob/master/lib/resque/plugins/lock_timeout.rb#L282), with the comment "Abort if another job holds the lock".

However, returning nil means the job is discarded. This breaks functionality documented [here](https://github.com/lantins/resque-lock-timeout/#job-identifierlock-key) whereby a "loose" identifier can be defined to enforce only one job in a class being run at a time. By discarding a job, we actually delete any jobs in that class which are reserved while the lock is held.

I believe the correct implementation would be to re-enqueue a job when a lock is held, much as [resque-lonely_job does](https://github.com/wallace/resque-lonely_job/blob/127855af1b9672f36d9331951bf13e63623df5d5/lib/resque-lonely_job.rb#L47).

**Comment by lantins** [comment]
Hi @sebbacon 

You can use the `lock_failed` callback to implement your own handling code when a job is locked.
You could also look at using resque-lock-timeout with the resque-retry plugin.

What do you think?

**Comment by sebbacon** [comment]
Hi @lantins. Both of those sound OK, but can I suggest it's a bug that the current behaviour isn't documented? It says in the README:

*The above modification will ensure only one job of class UpdateNetworkGraph is running at a time, regardless of the repo_id*

At our end there had been an assumption that the lock would not cause a job to be consumed silently, but simply to be deferred. I think others would assume that also.

**Comment by lantins** [comment]
@sebbacon Any better?

**Comment by sebbacon** [comment]
Looks good!
