### ISSUE TITLE
Does this work with Active Job?

### ISSUE THREAD

**Issue by popup-user** [lantins/resque-lock-timeout#30]
Hi, 
I've I'm using Resque with Active Job (using Rails 4.2.4), and I'm not clear on whether I can somehow just use this gem, or if I have to go back to using Resque the "old" way.

my current code looks like this:
/app/jobs/my_long_request_job.rb

``` ruby
class MyLongRequestJob < ActiveJob::Base
  queue_as :default

  def perform(request_id)
      request = MyRequest.find(request_id)
      request.long_running_process
  end
end
```

If you can let me know and/or update the documentation it would be very helpful!
Thanks!

**Comment by lantins** [comment]
I don't know, try adding `extend Resque::Plugins::LockTimeout` to your class and see if it works!

Let us know if it does.

**Comment by popup-user** [comment]
Ok, the app didn't crash, but when I set @lock_timeout = 350, I tested, sending two requests -- the lock was disregarded. The two jobs were immediately issued, one after the other - so _at minimum_, @lock_timeout doesn't seem to work, alas. :/. Thanks for your quick response. It would be great if the app could work with Active Job. Now I have consider porting them to work the "old" way.

**Comment by lantins** [comment]
If ActiveJob can work with Resque, there must be a way to use the plugins.

Wish I could help more, please do post back if you find a solution.

**Comment by popup-user** [comment]
I don't know how to solve the particular integration issue, but I do see that someone else posted an ActiveJob lock plugin for resque -- Perhaps by studying the source, something could be gleaned:
https://github.com/idolweb/activejob-lock 

I linked to this thread from here: https://github.com/resque/resque/issues/1354 -- so it seems the Resque project, itself is looking for answers.
Cheers!

**Comment by lantins** [comment]
If this can be done without complicating things I'd be happy to accept a PR.

I had a quick scan of that repo, but it didn't jump out at me what we could do.

Pull requests welcome :)
