### ISSUE TITLE
Jobs are not enqueued on multiple workers

### ISSUE THREAD

**Issue by anduong** [lantins/resque-lock-timeout#31]
Hi guys,

In development environment (I haven't pushed to production yet), I do

``` Ruby
rake resque:workers QUEUE='*' COUNT='3'
```

My class simply looks like this

``` Ruby
module CategoryServices
  class ShopifyNavigationManager
    extend Resque::Plugins::LockTimeout

    @queue = :shopify_navigation_manager
    @loner = false # I even set loner = false here.

    def self.perform(options = {})
       # execute something here.
    end
  end
end
```

When I enqueue jobs multiple times (more than 1, even > 3 which is number of workers)

``` Ruby
Resque.enqueue(CategoryServices::ShopifyNavigationManager)
```

The number of jobs in queue does not increase `Resque.size(:shopify_navigation_manager)` is still `0`.

But when I limit number of wokers to `1`

``` Ruby
rake resque:workers QUEUE='*' COUNT='1'
```

And then enqueue jobs multiple times, `Resque.size(:shopify_navigation_manager)`  > `0`

Can you please take a look? Thanks.

**Comment by lantins** [comment]
Hey,

Are you using the Loner plugin?

**Comment by lantins** [comment]
Also, are you checking the size of the queue when the workers are running or not?

**Comment by anduong** [comment]
@lantins : Thanks for you prompt reply.

I'm not using `Loner` plugin. 

Yes, I did check the size of the queue while the first job is being run by workers.

**Comment by lantins** [comment]
Okay, its like that ifs you had more then 1 worker, the other workers would have picked up the job, then failed because there was a lock.

Try queueing the jobs, without any workers running, and the counts should match what your expecting.

**Comment by anduong** [comment]
@lantins Thanks for your great support :smile: I will try testing queueing the jobs, without any workers running to check the counts.

But my scenario is kind of irritating. I just tell here. If you have any good idea, I will really appreciate it.
- After the user clicks on a button (say `Publish` button), I should run the job immediately. 
- 20 or whatever seconds laters, she makes changes and clicks `Publish` again. 
- 35 or whatever seconds later from the second time, she makes another changes and clicks one more time on `Publish` and goes to bed while the first job is still running. 

Therefore, I cannot enqueue 3 jobs at the same time. In other words, I cannot queue the jobs without any workers running because the first jobs should run immediately and I have no idea when she click `Publish` at second time.

**Comment by lantins** [comment]
Unfortunately, your going to need more then what this plugin provides, it will only get you part way there.

This plugin would only prevent jobs (that share a lock key) from running at the same time.

It sounds like you need something that will:
1. Prevent jobs from running at the same time.
2. If a job is already running, only allow 1 more job to be enqueued.
3. The 1 job that is queued needs to publish the most recent information, no matter how many enqueue requests happened between (so if the user clicks publish 5 times before the first job has finished, the queued job would 'ignore' clicks 2,3 and 4 and performs the update as if it was the final 5th click).

This plugin can help you with (1), you can use a `before_enqueue` hook to help you with (2) and you'll need to handle (3) when the job is performed.

Hope this helps!

**Comment by anduong** [comment]
@lantins Ohhhh, wow, you are really quick and smart! I did not explicitly mention (2) & (3) but you can get it by yourself :+1: 

> 2) If a job is already running, only allow 1 more job to be enqueued.
> 3) The 1 job that is queued needs to publish the most recent information, no matter how many enqueue > requests happened between (so if the user clicks publish 5 times before the first job has finished, the > queued job would 'ignore' clicks 2,3 and 4 and performs the update as if it was the final 5th click).

I already handled (3), and I think `before_enqueue` would help for (2). 
I think this issue is solved. You can close it.

Thank you very much for your great support though it is out of scope of the plugin :smiley:

**Comment by lantins** [comment]
:)

**Comment by anduong** [comment]
@lantins: I did it man!!! But I use `before_dequeue` instead. 
The queue now only allows one job to wait in while the formerly enqueued job is being executed by the running worker. And the waiting job is not fetched to execute by other free workers 

Just want to share for ones who will Google later and find this issue.

**Problem Description / Requirements (summarized by Antins)**

> 1. Prevent jobs from running at the same time.
> 2. If a job is already running, only allow 1 more job to be enqueued.
> 3. The 1 job that is queued needs to publish the most recent information, no matter how many enqueue requests happened between (so if the user clicks publish 5 times before the first job has finished, the queued job would 'ignore' clicks 2,3 and 4 and performs the update as if it was the final 5th click).

**Solution**

``` Ruby
def self.before_dequeue
  !locked? # The second job still waits in the queue until the worker (say #1) 
# finish the first job and will not be fetched to execute by other workers.
end
```

Beside that, this is also necessary

``` Ruby
QUEUE_CAPACITY = 1
@queue = :your_limit_queue_or_whatever_you_name_it

def self.background_jobs_available?
  Resque.size(@queue) < QUEUE_CAPACITY # only allow 1 job to wait in the queue. No more.
end
```

Credits go to @lantins first, then me.

**Comment by lantins** [comment]
Awesome, good job dude!

I'm sure future googles will appreciate you following this up.

**Comment by anduong** [comment]
Thanks dude! :smile:
